# import and take copy of the data

In [1]:
import pandas as pd
import numpy as np
import copy

### import data

In [2]:
business = pd.read_json(r"yelp_academic_dataset_business.json" , lines = True)
review = pd.read_json(r"yelp_academic_dataset_review.json" , lines = True)

### take copy of the data

In [3]:
bsn = copy.deepcopy(business)
rw = copy.deepcopy(review)

In [4]:
bsn.head(2)

,business_id,full_address,hours,open,categories,city,review_count,name,neighborhoods,longitude,state,stars,latitude,attributes,type
0,vcNAWiLM4dR7D2nwwJ7nCA,"4840 E Indian School Rd\nSte 101\nPhoenix, AZ ...","{'Tuesday': {'close': '17:00', 'open': '08:00'...",True,"[Doctors, Health & Medical]",Phoenix,7,"Eric Goldberg, MD",[],-111.983758,AZ,3.5,33.499313,{'By Appointment Only': True},business
1,JwUE5GmEO-sH1FuwJgKBlQ,"6162 US Highway 51\nDe Forest, WI 53532",{},True,[Restaurants],De Forest,26,Pine Cone Restaurant,[],-89.335844,WI,4.0,43.238893,"{'Take-out': True, 'Good For': {'dessert': Fal...",business

In [5]:
rw.head(2)

,votes,user_id,review_id,stars,date,text,type,business_id
0,"{'funny': 0, 'useful': 2, 'cool': 1}",Xqd0DzHaiyRqVH3WRG7hzg,15SdjuK7DmYqUAj6rjGowg,5,2007-05-17,dr. goldberg offers everything i look for in a...,review,vcNAWiLM4dR7D2nwwJ7nCA
1,"{'funny': 0, 'useful': 2, 'cool': 0}",H1kH6QZV7Le4zqTRNxoZow,RF6UnRTtG7tWMcrO2GEoAg,2,2010-03-22,"Unfortunately, the frustration of being Dr. Go...",review,vcNAWiLM4dR7D2nwwJ7nCA

In [83]:
class data_cleaning:
    
    #class attributes
    remove_zero_index = [] # to remove the index of zero category
    category_set = set() # set of all categories
    category_list= [] # make it list to organize it
    
    kw_index_list = [] # index of specified kw search
    
    data_log = dict() # every dataset ["name" : index_value]
    review_data_log = dict() # review data ["name" , index_value]
    
    #constructor
    def __init__(self , data , review_data , column):
        self.data = data
        self.column = column
        self.review_data = review_data
        
        for i in range(len(self.data)):
            filt = data.loc[i,str(column)]
            for j in range(len(filt)):
                data_cleaning.category_set.add(str(j))
        
        data_cleaning.category_list = list(data_cleaning.category_set)
    
    
    # function to remove the zero category in the data
    # function 0.0
    def error_zero(self):
        error_category_zero = dict()

        for i in range(len(self.data)):
            category = self.data.loc[i,"categories"]
            if (len(category) >= 1):
                pass
            else:
                error_category_zero[i] = self.data.loc[i,["business_id" , "name"]]
        data_cleaning.remove_zero_index = (pd.DataFrame(error_category_zero).T).index
    
    # function 0.1 / remove the zero index
    def remove_error_zero(self):
        self.data = self.data.drop(data_cleaning.remove_zero_index)
        self.data = self.data.reset_index(drop=True)
        print(f"the no. columns of the data is {self.data.shape[0]}")
        
    
    # function that return index of specific data with keywords
    # function 1
    def get_category(self , keywords):
        
        for i in range(len(self.data)):
            check_list = self.data.loc[i,str(self.column)]
            for j in range(len(check_list)):
                if check_list[j] in keywords:
                    data_cleaning.kw_index_list.append(i)
                    break
                    
    # function to seperate the data according to the index
    #function 2 
    def seperate_category(self , new_data_name):
        # saving the data to a dictionary to retrive it 
        data_cleaning.data_log[new_data_name] = data_cleaning.kw_index_list
        
        # Separating the review_business_data according to the index_list
        S_list_index = data_cleaning.data_log[new_data_name]
        business_list = self.data.loc[S_list_index,:]
        bus_list2 = list(business_list.business_id)

        rw_list_index = []
        for i in range(len(self.review_data)):
            filt = self.review_data.loc[i, "business_id"]
            if str(filt) in bus_list2:
                rw_list_index.append(self.review_data.index[i])

        data_cleaning.review_data_log[new_data_name] = rw_list_index
        return business_list

In [84]:
clean = data_cleaning(bsn , rw , "categories")

In [85]:
clean.error_zero()

In [86]:
clean.remove_error_zero()

the no. columns of the data is 41814

In [87]:
clean.data.shape

(41814, 15)

In [88]:
key_word_list = [ "Children\'s Clothing" , "Men\'s Clothing" , "Women\'s Clothing"]
clean.get_category(key_word_list)

In [89]:
len(clean.kw_index_list)

795

In [90]:
clean.data.shape

(41814, 15)

In [91]:
x = clean.seperate_category("men_women_child_cloths")

In [92]:
clean.review_data_log

{'men_women_child_cloths': [248,
  249,
  250,
  251,
  252,
  253,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  767,
  768,
  769,
  770,
  1061,
  1062,
  1063,
  1064,
  1248,
  1249,
  1250,
  15770,
  15771,
  15772,
  15773,
  15774,
  15775,
  15776,
  15777,
  15778,
  15779,
  15780,
  15781,
  15782,
  15783,
  15784,
  15785,
  15786,
  15787,
  15788,
  15789,
  15790,
  15791,
  15792,
  15793,
  15794,
  15795,
  15796,
  15797,
  15798,
  15799,
  15800,
  15801,
  15802,
  15803,
  15804,
  15805,
  15806,
  15807,
  15808,
  15809,
  15810,
  15811,
  15812,
  15813,
  15814,
  15815,
  15816,
  15817,
  15818,
  15819,
  15820,
  15821,
  15822,
  15823,
  15824,
  15825,
  15826,
  15827,
  15828,
  15829,
  15830,
  15831,
  15832,
  15833,
  15834,
  16388,
  16389,
  16390,
  16391,
  16392,
  16393,
  18779,
  18780,
  18781,
  18782,
  18783,
  18784,
  20457,
  20458,
  20459,
  20460,
  20461,
  20462,
  20463,
  20464,
  20465,
  20466,
  22000,
  22793,
  22794,
  22795,
  22796,
  22797,
  22798,
  22799,
  22800,
  22801,
  22802,
  22803,
  22804,
  22805,
  22806,
  22807,
  22808,
  22809,
  22810,
  22811,
  24351,
  24352,
  24353,
  27052,
  27053,
  27054,
  32643,
  32644,
  32645,
  32646,
  32647,
  32648,
  33673,
  33674,
  33675,
  33676,
  33677,
  33678,
  33964,
  33965,
  33966,
  34169,
  34170,
  34171,
  34172,
  34173,
  34186,
  34187,
  34188,
  34189,
  34190,
  34191,
  34192,
  34193,
  34194,
  34195,
  34196,
  34197,
  34198,
  34199,
  34200,
  34201,
  34202,
  34203,
  34204,
  34205,
  34977,
  34978,
  34979,
  34980,
  34981,
  34982,
  36271,
  36272,
  36273,
  36274,
  36275,
  41064,
  41065,
  41066,
  42652,
  42653,
  42654,
  42655,
  42656,
  43946,
  43947,
  43948,
  43949,
  43950,
  43951,
  43952,
  43953,
  43954,
  43955,
  43956,
  43957,
  43958,
  43959,
  43960,
  43961,
  44187,
  44188,
  44189,
  44190,
  44191,
  44192,
  44193,
  44194,
  44195,
  44196,
  44197,
  44198,
  44199,
  44200,
  44201,
  44568,
  44569,
  44570,
  44571,
  44572,
  44575,
  44576,
  44577,
  44578,
  44579,
  44580,
  44581,
  44582,
  44583,
  44584,
  44585,
  44608,
  44609,
  44610,
  44611,
  44612,
  44613,
  44614,
  44615,
  44616,
  44617,
  44618,
  44619,
  44620,
  44621,
  44691,
  44692,
  44693,
  44694,
  44695,
  46760,
  46761,
  46762,
  46763,
  46764,
  46765,
  46766,
  46767,
  46768,
  46769,
  46770,
  46771,
  46772,
  46773,
  46774,
  46775,
  46776,
  46777,
  47073,
  47074,
  47075,
  47076,
  47077,
  47078,
  47079,
  47080,
  47081,
  47498,
  47499,
  47500,
  47501,
  47502,
  47503,
  47504,
  47505,
  47506,
  47507,
  47508,
  47535,
  47536,
  47537,
  47538,
  47539,
  47540,
  47541,
  47542,
  49458,
  49459,
  49460,
  50848,
  50849,
  50850,
  50851,
  50852,
  50853,
  50898,
  50899,
  50900,
  53079,
  53080,
  53081,
  55441,
  55442,
  55443,
  55444,
  55445,
  55446,
  55447,
  55448,
  55449,
  55450,
  55451,
  55452,
  55453,
  55454,
  55455,
  55456,
  55457,
  55458,
  55459,
  55460,
  56654,
  56655,
  56656,
  57150,
  57151,
  57152,
  57176,
  57177,
  57178,
  57550,
  57551,
  57552,
  57580,
  57581,
  57878,
  57879,
  59295,
  59296,
  59297,
  59298,
  60816,
  60817,
  60818,
  60819,
  60820,
  60821,
  60822,
  60823,
  62439,
  62440,
  62441,
  62442,
  62443,
  62444,
  62445,
  62446,
  62447,
  62448,
  62449,
  63997,
  63998,
  63999,
  64000,
  64649,
  64650,
  64651,
  64652,
  64653,
  64916,
  64917,
  64918,
  64919,
  64920,
  65335,
  65336,
  65337,
  65338,
  65339,
  65340,
  65412,
  65413,
  65414,
  65415,
  65717,
  65718,
  65719,
  65720,
  66660,
  66661,
  66662,
  66663,
  66671,
  66672,
  66673,
  66674,
  66675,
  66676,
  66677,
  66678,
  66691,
  66692,
  66693,
  66694,
  66775,
  66776,
  66777,
  66778,
  66779,
  66780,
  67278,
  67279,
  67280,
  67306,
  67307,
  67308,
  67309,
  67529,
  67530,
  67531,
  67532,
  67533,
  67534,
  67535,
  67536,
  67537,
  67538,
  67539,
  67704,
  67705,
  67706,
  67707,
  67723,
  67724,
  67725,
  67726,
  67727,
  67728,
  67729,
  67730,
  67731,
  67940,
  67941,
  67942,
  67943,
  67944,
  67945,
  67946,
  67947,
  67948,
  67949,
  68662,
  68663,
  68664,
  68665,
  68666,
  68667,
  68668,
  72029,
  72030,
  72420,
  72421,
  72422,
  72423,
  72424,
  72425,
  72426,
  72427,
  72428,
  72429,
  72430,
  72431,
  72432,
  72433,
  72434,
  72435,
  72436,
  72437,
  72438,
  72439,
  72440,
  72743,
  72744,
  72745,
  72746,
  72747,
  72748,
  72749,
  72750,
  72751,
  72752,
  72753,
  72754,
  72755,
  72756,
  72757,
  72758,
  72759,
  74708,
  74709,
  74710,
  74711,
  74712,
  74713,
  75893,
  75894,
  75895,
  76250,
  76251,
  76252,
  76253,
  76254,
  76255,
  76256,
  76257,
  76572,
  76573,
  76675,
  76676,
  76677,
  76678,
  76679,
  76680,
  76681,
  76682,
  76683,
  76687,
  76688,
  77511,
  77512,
  77513,
  77514,
  77515,
  77516,
  77517,
  77518,
  77519,
  83195,
  83196,
  83197,
  83198,
  83199,
  83200,
  83201,
  83202,
  85291,
  85292,
  85293,
  85294,
  85295,
  85890,
  85891,
  85892,
  85893,
  86032,
  86033,
  86034,
  86035,
  86036,
  86037,
  86038,
  86039,
  86040,
  86041,
  87812,
  87813,
  87814,
  87815,
  87816,
  87817,
  87818,
  87819,
  87820,
  87821,
  89654,
  89655,
  89656,
  89657,
  89658,
  89659,
  89660,
  89661,
  90556,
  90557,
  90558,
  90559,
  90560,
  91255,
  91256,
  91257,
  91258,
  91259,
  91260,
  91530,
  91531,
  92339,
  92340,
  92341,
  92342,
  92343,
  92344,
  92345,
  92346,
  92347,
  92348,
  92349,
  92350,
  92351,
  92352,
  92353,
  92354,
  92355,
  93151,
  93152,
  93153,
  93154,
  93155,
  93156,
  93157,
  93158,
  93159,
  93160,
  93161,
  93211,
  93212,
  93213,
  93214,
  93649,
  93650,
  93651,
  93652,
  93653,
  93654,
  93655,
  93656,
  93657,
  93658,
  93659,
  93660,
  93661,
  93662,
  93663,
  93664,
  93665,
  93666,
  93667,
  93668,
  93669,
  93670,
  93671,
  93672,
  93673,
  93790,
  93791,
  93792,
  93793,
  93794,
  93795,
  93796,
  93797,
  93798,
  93799,
  93800,
  93801,
  93802,
  93803,
  93804,
  93805,
  94511,
  94512,
  94513,
  94514,
  101092,
  101093,
  101094,
  101095,
  102183,
  102184,
  102185,
  102186,
  102503,
  102504,
  102505,
  102506,
  106531,
  106532,
  106533,
  106534,
  106535,
  106536,
  106537,
  106538,
  106539,
  106540,
  106541,
  111428,
  111429,
  111430,
  111431,
  111432,
  113299,
  113300,
  113301,
  113302,
  113396,
  113397,
  113398,
  113399,
  113400,
  113401,
  113402,
  113403,
  113425,
  113426,
  113427,
  114240,
  114241,
  114242,
  114243,
  114244,
  114250,
  114251,
  114252,
  114253,
  114254,
  114255,
  114256,
  114257,
  114258,
  114259,
  114260,
  114261,
  114262,
  114263,
  114264,
  114265,
  114266,
  114267,
  114268,
  115143,
  115144,
  115145,
  115146,
  115147,
  115148,
  115149,
  115209,
  115210,
  115211,
  124246,
  124247,
  124248,
  124249,
  124250,
  129045,
  129046,
  129047,
  129048,
  129049,
  129050,
  129051,
  129052,
  129053,
  129054,
  129055,
  129056,
  129057,
  129058,
  129771,
  129772,
  129773,
  130438,
  130439,
  130440,
  130843,
  130844,
  130845,
  130846,
  130847,
  130848,
  132814,
  132815,
  132816,
  132820,
  132821,
  132822,
  132823,
  132824,
  132825,
  132826,
  132827,
  132828,
  132829,
  132830,
  134669,
  134670,
  134671,
  134672,
  134673,
  134674,
  135510,
  135511,
  135512,
  135513,
  138691,
  138692,
  138693,
  138694,
  138695,
  138696,
  138697,
  139690,
  139691,
  139692,
  139693,
  139694,
  139695,
  139696,
  147294,
  147295,
  147296,
  147297,
  147298,
  147299,
  148940,
  148941,
  149019,
  149020,
  149021,
  149022,
  149023,
  149889,
  149890,
  149891,
  149892,
  150705,
  150706,
  150707,
  152942,
  152943,
  152944,
  152945,
  152946,
  153550,
  153551,
  153552,
  154390,
  154391,
  154392,
  154932,
  154933,
  154934,
  154935,
  154936,
  156732,
  156733,
  156734,
  156735,
  156736,
  156737,
  156738,
  156739,
  156740,
  158058,
  158059,
  158066,
  158067,
  158068,
  158069,
  158070,
  158071,
  158072,
  158073,
  158074,
  158075,
  158076,
  158077,
  158078,
  158079,
  159801,
  159802,
  159803,
  161348,
  161349,
  161350,
  161351,
  161352,
  161353,
  161354,
  161355,
  161356,
  161357,
  161358,
  161359,
  161360,
  161361,
  161362,
  161363,
  161364,
  161365,
  161366,
  161367,
  161368,
  161369,
  161370,
  161371,
  161372,
  161373,
  161374,
  161375,
  161376,
  163963,
  163964,
  163965,
  163966,
  163967,
  164117,
  164118,
  164119,
  164120,
  164121,
  164122,
  164258,
  164259,
  164260,
  164261,
  164262,
  164263,
  164264,
  164265,
  164266,
  164267,
  164268,
  164269,
  164270,
  164271,
  164272,
  164273,
  164274,
  164275,
  164276,
  164277,
  164278,
  164279,
  164280,
  164281,
  164282,
  164283,
  164284,
  164533,
  164534,
  164886,
  164887,
  164888,
  164889,
  164890,
  164891,
  164892,
  164893,
  164894,
  164895,
  164896,
  164897,
  164898,
  164899,
  164900,
  164901,
  164902,
  164903,
  164904,
  164905,
  164906,
  164907,
  164908,
  164909,
  164910,
  167933,
  167934,
  ...]}

In [93]:
len(clean.review_data_log["men_women_child_cloths"])

6592

In [94]:
# %store bus

In [95]:
clean.seperate_category

In [96]:
x == list_of_bus_id

ValueError: Unable to coerce to Series, length must be 15: given 795

In [ ]:
list_of_bus_id

In [ ]:
%store -r list_of_bus_id

note --> list_of_bus_id != business_list